"""added coordinates

Revision ID: 028620863d3c
Revises: 5cd20ca86545
Create Date: 2025-04-30 23:51:37.405155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028620863d3c'
down_revision = '5cd20ca86545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('from_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('to_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('to_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.drop_column('to_lng')
        batch_op.drop_column('to_lat')
        batch_op.drop_column('from_lng')
        batch_op.drop_column('from_lat')

    # ### end Alembic commands ###
