"""deletedride

Revision ID: 373d0974ee3c
Revises: 2f52a643030d
Create Date: 2025-05-01 21:09:06.630669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373d0974ee3c'
down_revision = '2f52a643030d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_ride_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('travel_time', sa.Time(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_ride')
    # ### end Alembic commands ###
