"""test2

Revision ID: 5cd20ca86545
Revises: ea6c075f49ea
Create Date: 2025-04-30 00:15:04.209045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cd20ca86545'
down_revision = 'ea6c075f49ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.drop_column('temp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
