""" adddded gender

Revision ID: 61d79c56f254
Revises: 
Create Date: 2025-04-29 20:51:19.434301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d79c56f254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('require_verification', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.drop_column('require_verification')
        batch_op.drop_column('gender_preference')

    # ### end Alembic commands ###
