"""addfk

Revision ID: a0068c0b16f9
Revises: 373d0974ee3c
Create Date: 2025-05-01 21:17:04.333971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0068c0b16f9'
down_revision = '373d0974ee3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deleted_ride', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deleted_ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
