"""test

Revision ID: ea6c075f49ea
Revises: 61d79c56f254
Create Date: 2025-04-29 21:10:09.602678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6c075f49ea'
down_revision = '61d79c56f254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_post', schema=None) as batch_op:
        batch_op.drop_column('temp')

    # ### end Alembic commands ###
